version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build(deps)"
    groups:
      python-patch-minor:
        update-types: ["minor", "patch"]
      python-major:
        update-types: ["major"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build(deps)"
    groups:
      github-actions:
        patterns: ["*"]
